services:
  bc-mysql:
    image: mysql:8.0
    container_name: bc-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - bluecherry_net
    volumes:
      - ./database:/var/lib/mysql
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      MYSQL_ROOT_PASSWORD: mysqladminpass
      TZ: America/Los_Angeles

  bluecherry:
    image: bluecherrydvr/bluecherry:latest
    container_name: bc-server
    cap_add:
      - NET_BIND_SERVICE
    build:
      context: ./server/
      network: bluecherry_net
      args:
        MYSQL_ADMIN_PASSWORD: mysqladminpass
        BLUECHERRY_DB_PASSWORD: mysqlbluecherrypass
    restart: unless-stopped
    networks:
      - bluecherry_net
    volumes:
      - ./recordings:/var/lib/bluecherry/recordings
      - ./data/bconf:/var/lib/bluecherry/.local/share/data/bconf
      - ./data/letsencrypt:/usr/share/bluecherry/nginx-includes/letsencrypt
      - ./data/backups:/usr/share/bluecherry/backups
    # Enable this only if you have a supported VAAPI device and /dev/dri exists on the host system.
    # devices:
    #   - /dev/dri:/dev/dri
    ports:
      - "7001:7001/tcp"
      - "7002:7002/tcp"
    env_file:
      - ./.env
    depends_on:
      - bc-mysql

networks:
  bluecherry_net:
    name: bluecherry_net
